export const ENV = {
  // DB Configs
  DB_NAME: 'DB_NAME',
  DB_TYPE: 'DB_TYPE',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USER: 'DB_USER',
  DB_PASSWORD: 'DB_PASSWORD',

  // JWT Secrets
  JWT_EXPIRE: 'JWT_EXPIRE',
  JWT_SECRET: 'JWT_SECRET',

  // Google Client
  GOOGLE_CLIENT_ID: 'GOOGLE_ID',
  GOOGLE_SECRET: 'GOOGLE_SECRET',
  GOOGLE_CALLBACK: 'GOOGLE_CALLBACK',

  // Github Client
  GITHUB_CLIENT_ID: 'GITHUB_CLIENT_ID',
  GITHUB_SECRET: 'GITHUB_SECRET',
  GITHUB_CALLBACK: 'GITHUB_CALLBACK',

  // SendGrid
  SENDGRID_SECRET: 'SENDGRID_SECRET',
  SENDGRID_EMAIL: 'SENDGRID_EMAIL',
  SENDGRID_TEMPLATE: 'SENDGRID_TEMPLATE',
};
